name: Build docker for all branches

on:
  push:
    branches-ignore:
      - 'develop'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn install --file pom.xml
      - name: Upload war
        uses: actions/upload-artifact@v2
        with:
          name: war
          path: target/*.war
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build
        id: download
        uses: actions/download-artifact@v2
        with:
          name: war
          path: target/
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "::set-output name=prop::$(echo ${GITHUB_REF#refs/heads/})"
      - run: echo "Current branch ${{steps.extract_branch.outputs.prop}}"
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: opherogel/queen-back-office
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: ${{steps.extract_branch.outputs.prop}}
